---
class: 4
flags: 0x0000
unid: OF7B8C4DCCC3DFE761-ON006B0ED385257AAA
items:
  - name: $DesignerVersion
    type: text
    data: 8.5.4
    signed: true
  - name: $FileNames
    type: text
    data: ".settings/.jsdtscope"
    signed: true
  - name: $Flags
    type: text
    data: ~C4g
  - name: $TITLE
    type: text
    data: ".settings/.jsdtscope"
  - name: $FileData
    type: composite
    signed: true
    nonsummary: true
remaining: []