---
ACL:
  opaque: |
    Q0ECAEoBBQAAAAAABQAoABAAeACYAAAAAAAoAAQAAAAEACgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAALYAAAAAAAAA3gAAAAAAAAAAAPwAAAAAAAAAAAAAAEVBBAAAAAAAAAAAAAAABAYJAC1EZWZhdWx0
    LQAAAEVBAAAAAAAAAAAAAAAARhASAE90aGVyRG9tYWluU2VydmVycwDdAABFQQAAAAAAAAAAAAAAAAQQ
    CQBBbm9ueW1vdXMAIgFFQQYAAAAAAAAAAAAAAPgHEQBMb2NhbERvbWFpbkFkbWlucwAAAEVBBgAAAAAA
    AAAAAAAA2gcSAExvY2FsRG9tYWluU2VydmVycwDdaGVyRG9tYWluU2VydmVycwDd3d0=
DBOptions: 0x00000000
DBInfo:
  FTIndexPriority: 3
  FTOptions: 0x0044
  FTStopFile: ""
  FTThesaur: ""
  Flags: 0x0000
  MajorVersion: 1
  MinorVersion: 0
  Options: 0x0000
  Spare1: 0